saveExact: true
engineStrict: true
minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true
trustPolicy: "no-downgrade"
trustPolicyExcludePrune: true
allowBuilds:
  "@prisma/engines": true
  "@swc/core": true
  prisma: true
  baileys: true
  protobufjs: true
minimumReleaseAgeExclude:
  - "@nestjs/config@12.0.1"
  - dotenv@18.0.3
  - "@ai-sdk/gateway@4.0.108"
  - "@ai-sdk/provider-utils@5.0.57"
  - ai@7.0.133
  - "@ai-sdk/provider@4.0.25"
